### PR TITLE
Fix #1: Fix windows required permissions for .env

### LINKED ISSUE #1: Windows WSL .env file permissions problem
`envy` requires you to put `600` as file permission on `.env`. Alas if your workspace is in the Windows land you cannot change the file permission from your bash environment. The problem is that Windows' permissions system is not as granular as Linux' is. You cannot set a `600` on it (at least I haven't found a way) however you can set `666`, `000` or `777`.

One way to solve this is changing the permissions requirements based on the platform running `envy`, we could settle for `666` when `process.platform === 'win32'`.

### PR DESCRIPTION
**Pull request by Nargonath**

### CODE REVIEW

**Comment by Nargonath** [comment]
I tried to add some tests to verify this behavior. I cannot run the tests suite right now as I'm on windows and all the prepare `chmod` command do not work in my case. I don't have my linux machine close by so if you don't mind testing that my test runs successfully.

File: index.js [hunk 1]
```diff
@@ -61,7 +67,10 @@ const envy = (input) => {
         return filterObj(camelizedGlobalEnv, camelizedExampleEnvKeys);
     }
 
-    if (checkMode(envPath, permissionMask) !== ownerReadWrite) {
+    if (isWindows() && checkMode(envPath, permissionMask) !== windowsPermission) {
+        throw new Error(`File permissions are unsafe. Make them 666 '${envPath}'`);
```
Comment (sholladay) [inline index.js]: > Make them 666

But the closest you can make them is 555, right? And if you somehow found a way to make them 666, this would fail anyway.

Also, is there a way to make them 555 from the command line on Windows? Would be nice to tell the user how to fix it. From what I read, maybe `icacls` could do it.

An alternative approach we could take here would be:

```js
if (checkMode(envPath, num.S_IWGRP | num.S_IWOTH) === 0) {
    throw new Error('...');
}
```

That asserts that the writable bits for the "group" and "others" are off, as opposed to checking that all readable and executable bits are on and all writable bits are off.

File: package.json [hunk 2]
```diff
@@ -31,7 +31,8 @@
     "dependencies": {
         "camelcase": "^4.1.0",
         "camelcase-keys": "^4.1.0",
-        "filter-obj": "^1.1.0"
+        "filter-obj": "^1.1.0",
+        "is-wsl": "1.1.0"
```
Comment (sholladay) [inline package.json]: Missing the `^`

File: test.js [hunk 3]
```diff
@@ -64,6 +64,19 @@ test('requires secure file permissions on .env', (t) => {
...
 
+test('requires secure file permissions on .env in windows land', (t) => {
+    const previousPlatform = process.platform;
+    process.platform = 'win32';
+
+    const err = t.throws(() => {
+        fixture('unsafe-perm-windows-env-777');
+    }, Error);
+    const filepath = path.join('fixture', 'unsafe-perm-env-640', '.env');
+    t.is(err.message, `File permissions are unsafe. Fix: chmod 600 '${filepath}'`);
```
Comment (sholladay) [inline test.js]: The `Fix:` part of this error message doesn't align with what is thrown in the Windows environment.

File: test.js [hunk 4]
```diff
@@ -64,6 +64,19 @@ test('requires secure file permissions on .env', (t) => {
...
 });
 
+test('requires secure file permissions on .env in windows land', (t) => {
+    const previousPlatform = process.platform;
+    process.platform = 'win32';
+
+    const err = t.throws(() => {
+        fixture('unsafe-perm-windows-env-777');
+    }, Error);
+    const filepath = path.join('fixture', 'unsafe-perm-env-640', '.env');
```
Comment (sholladay) [inline test.js]: The filepath here doesn't match the fixture that was actually used.

**Review by sholladay — CHANGES_REQUESTED** [review]

File: package.json (hunk 2 above)
Comment (Nargonath) [reply package.json]: Indeed sorry, my default NPM settings are `--save-exact`. I'll change it.

File: test.js (hunk 4 above)
Comment (Nargonath) [reply test.js]: Oups sorry, went a bit too quick on this one and the previous one as well.

File: package.json (hunk 2 above)
Comment (sholladay) [reply package.json]: Yeah, I figured. I had that for a while, too. Gave it up because it is a false sense of security. It only locks down your top level dependencies. If any of those dependencies have semver ranges and a sub-dependency violates semver (or has other issues), you're probably still going to be exposed to it. Updates tend to be good, anyway. And when you really need to lock things down properly, there is shrinkwrap.

**Review by sholladay — APPROVED** [review]

File: package.json (hunk 2 above)
Comment (Nargonath) [reply package.json]: Yeah I might reconsider it indeed.

File: index.js (hunk 1 above)
Comment (Nargonath) [reply index.js]: I'm not aware of a command line way. I've been doing it from windows configuration panels but indeed it would be nice to do it with the command line. I wonder if you can call that command from bash or if you want to open `Powershell` or something similar.

Comment (Nargonath) [reply index.js]: Do you want me to update the PR with the "group" and "others" write bits off?

**Comment by sholladay** [comment]
Thanks, @Nargonath! ❤️ 

Windows support has been released.
